## Importar librerías y JSON

In [ ]:
import json
import pandas as pd

path = "/content/logs_KX7A_20260220-1944_GrupoB.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

## Arreglar formato

In [ ]:
# arreglar anidamiento doble
if isinstance(data, list) and len(data) == 1 and isinstance(data[0], list):
    records = data[0]
else:
    records = data

df = pd.json_normalize(records)

df.head()

,hora,nombrecompletodelusuario,usuarioafectado,contextodelevento,componente,nombredelevento,descripcin,origen,direccinip
0,"20/02/26, 19:44:25",KARLA VERONICA RODRIGUEZ LOZANO,-,Curso: Programación de Base de Datos - KX7A KX...,Bitácoras,Reporte de bitácora visto,The user with id &#039;116&#039; viewed the lo...,web,177.230.139.62
1,"20/02/26, 19:43:57",KARLA VERONICA RODRIGUEZ LOZANO,-,Curso: Programación de Base de Datos - KX7A KX...,Bitácoras,Reporte de bitácora visto,The user with id &#039;116&#039; viewed the lo...,web,177.230.139.62
2,"20/02/26, 19:43:46",KARLA VERONICA RODRIGUEZ LOZANO,-,Curso: Programación de Base de Datos - KX7A KX...,Bitácoras,Reporte de bitácora visto,The user with id &#039;116&#039; viewed the lo...,web,177.230.139.62
3,"20/02/26, 19:43:21",KARLA VERONICA RODRIGUEZ LOZANO,-,Curso: Programación de Base de Datos - KX7A KX...,Bitácoras,Reporte de bitácora visto,The user with id &#039;116&#039; viewed the lo...,web,177.230.139.62
4,"20/02/26, 19:42:43",KARLA VERONICA RODRIGUEZ LOZANO,-,Curso: Programación de Base de Datos - KX7A KX...,Bitácoras,Reporte de bitácora visto,The user with id &#039;116&#039; viewed the lo...,web,177.230.139.62

### Convertir formato de fecha

In [ ]:
df["hora"] = pd.to_datetime(
    df["hora"],
    format="%d/%m/%y, %H:%M:%S",
    errors="coerce"
)

## Extraer fechas

In [ ]:
df["fecha"] = df["hora"].dt.date

In [ ]:
daily_frequency = (
    df.groupby(
        ["fecha", "nombrecompletodelusuario", "nombredelevento"]
    )
    .size()
    .reset_index(name="frecuencia")
)

daily_frequency.head()

,fecha,nombrecompletodelusuario,nombredelevento,frecuencia
0,2024-08-16,Admin User,Curso restaurado,1
1,2024-08-16,Admin User,Curso visto,1
2,2024-08-16,Admin User,Elemento de calificación actualizado,83
3,2024-08-16,Admin User,Elemento de calificación creado,92
4,2024-08-16,Admin User,Evento de calendario actualizado,2

## Formato legible (Usuario - Eventos)

In [ ]:
pivot_frequency = daily_frequency.pivot_table(
    index=["fecha", "nombrecompletodelusuario"],
    columns="nombredelevento",
    values="frecuencia",
    fill_value=0
).reset_index()

pivot_frequency.head(200)

# Crear pivot
pivot_frequency = daily_frequency.pivot_table(
    index=["fecha", "nombrecompletodelusuario"],
    columns="nombredelevento",
    values="frecuencia",
    fill_value=0
).reset_index()

nombredelevento,fecha,nombrecompletodelusuario,Agrupamiento creado,Agrupamiento eliminado,Archivo ZIP de carpeta descargado,Calificación eliminada,Comentario creado,Comentario eliminado,Confirmación de remoción de envío vista.,Curso actualizado,...,Sección de curso eliminada,Tabla para calificar vista,Terminó reinicio de curso,Todos los envíos están siendo descargados.,Tour iniciado,Tour terminado,Usuario des-inscrito (dado de baja) del curso,Usuario inscrito en curso,Ítem creado,Ítem eliminado
0,2024-08-16,Admin User,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
1,2024-08-19,ANGEL GUILLERMO HERRERA ALVARADO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,2024-08-19,ARGENIS EDEL ESQUIVEL VELAZQUEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
3,2024-08-19,BERTHA JOHANA ORONA JIMENEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,2024-08-19,BRENDA NOHEMI FLORES CERDA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2024-09-04,MARCO ANTONIO GONZALEZ JR.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,2024-09-04,YELTSIN ALISGHERY SANCHEZ HERRERA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,2024-09-05,ANGEL GUSTAVO PULIDO VALDEZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,2024-09-05,EMMANUEL TADEO ROCHA RIVAS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,2024-09-05,ERNESTO ALONSO MORENO REYES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pivot_frequency.columns.name = None

## Exportar a excel

In [ ]:
pivot_frequency.to_excel("daily_frequency_pivot.xlsx", index=False)

## Opciones display

In [ ]:
## mostrar tamaño del JSON
df.shape

In [ ]:
df

## Exportar

In [ ]:
# Export a Excel
daily_frequency.to_excel("daily_frequency.xlsx", index=False)